import Head from "next/head";
import styles from "../styles/Layout.module.css";
import "antd/dist/antd.css";
import axios from "axios";
import { BlogList, Header } from "../components";

export default function Home({ posts }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <div>
          <Header title="Bloggs" />
        </div>
        {posts === undefined ? <h2>Loading...</h2> : <BlogList blogs={posts} />}
      </div>
    </div>
  );
}

export const getStaticProps = async () => {
  let posts;
  try {
    const { data, status } = await axios.get(
      "https://practice-server-with-database.rupamdas.repl.co/posts"
    );
    if (status === 200) {
      posts = data.posts;
    }
  } catch (error) {
    console.log(error);
  }
  return {
    props: {
      posts,
    },
  };
};
